### ISSUE TITLE
Merge with content-generator

### ISSUE THREAD

**Issue by timuric** [auxdesigner/Sketch-Plugin---NumGen#1]
Hey, great plugins! 
I read your post and noticed you mentioned that you use https://github.com/timuric/Content-generator-sketch-plugin would you consider merging? I receive often requests for random numbers, our plugins solve similar problems would be nice to group them in one repo :)

**Comment by auxdesigner** [comment]
Hi there,
Thanks for reaching out. Absolutely! I think merging is a great idea.
I'm open to however you want to do it :-)

**Comment by timuric** [comment]
@auxdesigner I added you as a collaborator. Maybe we can add your plugins into Numbers folder?

**Comment by timuric** [comment]
@auxdesigner Would you mind adding it? We can experiment on the beta branch ;)

**Comment by auxdesigner** [comment]
Sounds good! I'll update it :-)

**Comment by auxdesigner** [comment]
@timuric Just pushed to the beta branch!

**Comment by timuric** [comment]
@auxdesigner Awesome! I have published it, and added you to the list of contributors.
